version: '3'

services:
  mqtt:
    container_name: mqtt_broker
    build: ./mqtt_broker
    restart: always
    tty: true
    ports:
      - "1883:1883"
    networks:
      - network-internal
  
  status_machine:
    container_name: status_machine
    build: ./status_machine
    restart: always
    tty: true
    command: python main.py
    volumes: 
      - ./status_machine:/app
    networks:
      - network-internal
    depends_on: 
      - mqtt

networks: 
  network-internal:
    driver: bridge
